version: '1'
services:
  nodeapp:
    container_name: unisystem
    image: unisystem:1.0.1
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET_KEY=eyJ1c2VyIjp7Il9pZCI6IjY0NTNmYWI5YTQ2YWY4N
      - MONGODB_URL=mongodb://mongo:27017/IE-HW2
      - port=3000
    networks:
      - unisystem-network
    depends_on:
      - mongo
    links:
      - mongo
  
  mongo:
    container_name: unisystem-mongodb
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - unisystem-network

volumes:
  mongo-data:

networks:
  unisystem-network:
